# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS-10.14'


steps:

#- task: Cache@2
#  inputs:
#    key: 'pods | "$(Agent.OS)" | Podfile.lock'
#    path: 'Pods'
#    cacheHitVar: 'PODS_CACHE_RESTORED'

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: false

- task: CmdLine@2
  inputs:
    script: 'pod deintegrate' 

- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  inputs:
    scheme: 'demo-temporario'
    sdk: 'iphoneos'
    configuration: 'Release'
    #xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcWorkspacePath: 'demo-temporario.xcworkspace'
    xcodeDeveloperDir: '/Applications/Xcode_11.2.1.app/Contents/Developer'
    xcodeVersion: 'specifyPath'
    packageApp: false
